In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('data/mnist_train.csv')

In [3]:
df_train.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
df_train['label'].unique()

array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8])

In [5]:
trainer1_df = df_train[(df_train['label']==0) | \
                       (df_train['label']==1) | \
                       (df_train['label']==2)]

trainer2_df = df_train[(df_train['label']==3) | \
                       (df_train['label']==4) | \
                       (df_train['label']==5) ]

trainer3_df = df_train[(df_train['label']==6) | \
                       (df_train['label']==7) | \
                       (df_train['label']==8) | \
                       (df_train['label']==9)]

In [6]:
print(trainer1_df['label'].unique())
print(trainer2_df['label'].unique())
print(trainer3_df['label'].unique())

[0 1 2]
[5 4 3]
[9 6 7 8]


In [7]:
print(trainer1_df.shape)
print(trainer2_df.shape)
print(trainer3_df.shape)

(18623, 785)
(17394, 785)
(23983, 785)


In [8]:
trainer1_df.to_csv('data/trainer1.csv', index=False)
trainer2_df.to_csv('data/trainer2.csv', index=False)
trainer3_df.to_csv('data/trainer3.csv', index=False)